---
openapi: 3.0.3
info:
  title: Documentação da integração interna do Accounts
  description: Esta é a documentação das interfaces REST do Accounts
  contact:
    name: Equipe de desenvolvimento
    email: desenvolvimento@hivecloud.com.br
  version: 1.0
servers:
  - url: /accounts/api
    description: Servidor Local com /Accounts
  - url: /api
    description: Servidor Local sem /Accounts
tags:
  - name: Central Emissao V1
    description: Serviços básicos da Central de Emissão
  - name: Empresa
    description: Serviços básicos da entidade Empresa
  - name: Empresa Produto Log
    description: Controller for EmpresaProdutoLog
  - name: Organizacao Acesso
    description: Serviços básicos da entidade OrganizaçãoAcesso
  - name: Organizacao
    description: Serviços básicos da entidade Organização
  - name: Pesquisa V1
    description: Serviços básicos da Pesquisa
paths:
  /v1/central-emissao/validar-email:
    post:
      tags:
        - Central Emissao V1
      operationId: CentralEmissaoV1ControllerImp.validarEmail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CentralEmissaoValidarEmailDto'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CentralEmissaoValidarEmailDto_1'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
      x-operation-name: validarEmail
  /v1/organizacoes/{organizacaoId}/empresas:
    get:
      tags:
        - Empresa
      operationId: EmpresaControllerImp.listEmpresa
      description: Recupera uma Coleção de Empresas baseado no parâmetro informado
      parameters:
        - name: organizacaoId
          description: ID da Organizacao
          in: path
          required: true
          schema:
            type: string
        - name: pageNumber
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: campoPesquisa
          in: query
          required: false
          schema:
            type: string
        - name: cpfCnpj
          description: Cnpj Exato da Empresa
          in: query
          required: false
          schema:
            type: string
      responses:
        200:
          description: Uma Coleção de Empresas
          content:
            application/json:
              schema:
                type: object
                properties:
                  pageMetadata:
                    $ref: '#/components/schemas/PageMetadata'
                  nextLink:
                    type: string
                  previousLink:
                    type: string
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/EmpresaDtoLista'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
      x-operation-name: listEmpresa
    post:
      tags:
        - Empresa
      operationId: EmpresaControllerImp.criarEmpresa
      description: Criar um Empresa para uma determinada Organizacao
      parameters:
        - name: organizacaoId
          description: ID da Organizacao
          in: path
          required: true
          schema:
            type: string
        - name: tenant-origem
          description: Tenant da empresa da requisição
          in: header
          required: false
          schema:
            type: string
        - name: id-origem
          description: ID da empresa da requisição
          in: header
          required: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CriarEmpresaDto'
        description: Dados da Empresa que está sendo criado
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Void'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
      x-operation-name: criarEmpresa
  /v1/organizacoes/{organizacaoId}/empresas/{id}:
    get:
      tags:
        - Empresa
      operationId: EmpresaControllerImp.getEmpresa
      description: Recupera uma Empresa Acesso a partir da Identificação
      parameters:
        - name: organizacaoId
          description: ID da Organização
          in: path
          required: true
          schema:
            type: string
        - name: id
          description: ID da Empresa
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Empresa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmpresaDto'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
      x-operation-name: getEmpresa
    put:
      tags:
        - Empresa
      operationId: EmpresaControllerImp.editarEmpresa
      description: Editar uma Empresa existente
      parameters:
        - name: organizacaoId
          description: ID da Organizacao
          in: path
          required: true
          schema:
            type: string
        - name: id
          description: ID da Empresa
          in: path
          required: true
          schema:
            type: string
        - name: tenant-origem
          description: Tenant da empresa da requisição
          in: header
          required: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CriarEmpresaDto'
        description: Dados da Empresa que está sendo editada
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Void'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
      x-operation-name: editarEmpresa
  /v1/empresas/{empresaId}/log:
    get:
      tags:
        - Empresa Produto Log
      operationId: EmpresaProdutoLogControllerImp.listar
      description: List EmpresaProdutoLog by empresa id with optional filters
      parameters:
        - name: empresaId
          description: ID of the empresa
          in: path
          required: true
          schema:
            type: string
        - name: pageNumber
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: campoPesquisa
          in: query
          required: false
          schema:
            type: string
        - name: produto
          description: Filtro por produto
          in: query
          required: false
          schema:
            type: string
        - name: sucesso
          description: Filtro por sucesso ou falha
          in: query
          required: false
          schema:
            type: boolean
      responses:
        200:
          description: List of EmpresaProdutoLogDto
          content:
            application/json:
              schema:
                type: object
                properties:
                  pageMetadata:
                    $ref: '#/components/schemas/PageMetadata'
                  nextLink:
                    type: string
                  previousLink:
                    type: string
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/EmpresaProdutoLogDto'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
      x-operation-name: listar
  /v1/empresas/{empresaId}/log/{logId}/reenviar:
    post:
      tags:
        - Empresa Produto Log
      operationId: EmpresaProdutoLogControllerImp.reenviar
      description: Resend a log entry
      parameters:
        - name: empresaId
          in: path
          required: true
          schema:
            type: string
        - name: logId
          description: ID of the log entry
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: The updated log entry
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Void'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
      x-operation-name: reenviar
  /v1/organizacoes:
    post:
      tags:
        - Organizacao
      operationId: OrganizacaoControllerImp.criarOrganizacao
      description: Criar um Organizacao
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CriarOrganizacaoDto'
        description: Dados da Organizacao
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Void'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
      x-operation-name: criarOrganizacao
  /v1/organizacoes/por-usuario/{login}:
    get:
      tags:
        - Organizacao
      operationId: OrganizacaoControllerImp.getPorUsuario
      description: Recupera as Organizações às quais o usuário tem acesso
      parameters:
        - name: login
          description: O login do usuário que tem acesso às Organizações
          in: path
          required: true
          schema:
            type: string
        - name: pageNumber
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: campoPesquisa
          in: query
          required: false
          schema:
            type: string
      responses:
        200:
          description: Uma Coleção de Organizações
          content:
            application/json:
              schema:
                type: object
                properties:
                  pageMetadata:
                    $ref: '#/components/schemas/PageMetadata'
                  nextLink:
                    type: string
                  previousLink:
                    type: string
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/OrganizacaoDtoLista'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
      x-operation-name: getPorUsuario
  /v1/organizacoes/{id}:
    get:
      tags:
        - Organizacao
      operationId: OrganizacaoControllerImp.get
      description: Recupera uma Organização a partir da Identificação
      parameters:
        - name: id
          description: ID da Organização
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Organização
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizacaoDto'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
      x-operation-name: get
  /v1/organizacoes/{organizacaoId}/acesso:
    get:
      tags:
        - Organizacao Acesso
      operationId: OrganizacaoAcessoControllerImp.listAcesso
      description: Recupera uma Coleção de Organização Acessos baseado no parâmetro
      parameters:
        - name: organizacaoId
          description: ID da Organizacao
          in: path
          required: true
          schema:
            type: string
        - name: pageNumber
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: campoPesquisa
          in: query
          required: false
          schema:
            type: string
        - name: login
          description: Login do usuário associado á regra de acesso
          in: query
          required: false
          schema:
            type: string
      responses:
        200:
          description: Uma Coleção de Organização Acessos
          content:
            application/json:
              schema:
                type: object
                properties:
                  pageMetadata:
                    $ref: '#/components/schemas/PageMetadata'
                  nextLink:
                    type: string
                  previousLink:
                    type: string
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/OrganizacaoAcessoDto'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
      x-operation-name: listAcesso
    post:
      tags:
        - Organizacao Acesso
      operationId: OrganizacaoAcessoControllerImp.criarAcesso
      description: Criar um Acesso para uma determinada Organizacao
      parameters:
        - name: organizacaoId
          description: ID da Organizacao
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CriarOrganizacaoAcessoDto'
            examples:
              EXEMPLO_ADM:
                perfil: ADMIN
                login: usuarioValido@teste.com
              EXEMPLO_USER:
                perfil: USER
                login: usuarioValido@teste.com
        description: Dados do Acesso que está sendo criado
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Void'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
      x-operation-name: criarAcesso
  /v1/organizacoes/{organizacaoId}/acesso/{id}:
    get:
      tags:
        - Organizacao Acesso
      operationId: OrganizacaoAcessoControllerImp.getAcesso
      description: "Recupera uma Organização Acesso a partir da Identificação, praticamente\
        \ nunca será utilizada"
      parameters:
        - name: organizacaoId
          description: ID da Organização
          in: path
          required: true
          schema:
            type: string
        - name: id
          description: ID da Organização Acesso
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Organização Acesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizacaoAcessoDto'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
      x-operation-name: getAcesso
    delete:
      tags:
        - Organizacao Acesso
      operationId: OrganizacaoAcessoControllerImp.deleteAcesso
      description: "Remove uma Organização Acesso a partir da Identificação, praticamente\
        \ nunca será utilizada"
      parameters:
        - name: organizacaoId
          description: ID da
          in: path
          required: true
          schema:
            type: string
        - name: id
          description: ID da Organização Acesso
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Organização Acesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Void'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
      x-operation-name: deleteAcesso
  /v1/pesquisas/registrar-dados:
    post:
      tags:
        - Pesquisa V1
      operationId: PesquisaV1ControllerImp.registrarPesquisaDados
      description: Registra os dados da pesquisa.
      parameters:
        - name: produto
          description: O nome do produto enviado no cabeçalho da requisição.
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PesquisaDadosDto'
        description: O DTO contendo os dados da pesquisa.
      responses:
        200:
          description: ResponseEntity contendo uma mensagem de sucesso.
          content:
            text/plain:
              schema:
                type: string
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
      x-operation-name: registrarPesquisaDados
  /v1/pesquisas/retornar-pesquisa:
    get:
      tags:
        - Pesquisa V1
      operationId: PesquisaV1ControllerImp.retornarPesquisa
      description: Retorna os dados da pesquisa para o período atual.
      responses:
        200:
          description: ResponseEntity contendo o DTO do período da pesquisa.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PesquisaPeriodoDto'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
      x-operation-name: retornarPesquisa
components:
  schemas:
    CentralEmissaoValidarEmailCertificadoDto:
      type: object
      properties:
        tipo:
          type: string
        dataValidade:
          type: string
        statusVencimento:
          type: string
    CentralEmissaoValidarEmailDadosContaDto:
      type: object
      properties:
        plano:
          type: string
        tenantCte:
          type: string
        tenantMdfe:
          type: string
        idSistemaPagamento:
          type: string
        idEmpresaCte:
          type: string
        cnpjCte:
          type: string
        idEmpresaMdfe:
          type: string
        cnpjMdfe:
          type: string
        certificado:
          $ref: '#/components/schemas/CentralEmissaoValidarEmailCertificadoDto'
        emailsVinculados:
          type: array
          items:
            type: string
    CentralEmissaoValidarEmailDto:
      type: object
      properties:
        email:
          type: string
    CentralEmissaoValidarEmailDto_1:
      type: object
      properties:
        status:
          type: string
        mensagem:
          type: string
        dadosConta:
          $ref: '#/components/schemas/CentralEmissaoValidarEmailDadosContaDto'
    CertificadoDto:
      description: "DTO de Certificado Digital, representa informações sobre o certificado\
        \ digital da empresa."
      type: object
      properties:
        validadeCertificado:
          description: Data de validade do certificado
          type: string
          format: date-time
        tokenCertificado:
          description: Token do certificado digital
          type: string
        tipoCertificado:
          description: Tipo do certificado digital
          $ref: '#/components/schemas/TipoCertificadoDto'
    CnaeDto:
      type: object
      properties:
        codigo:
          description: Código Cnae
          type: string
        descricao:
          description: Descrição do Cnae
          type: string
    CriarEmpresaDto:
      description: "DTO de Empresa, usado para a ação de cadastramento"
      required:
        - tipoDocumento
        - cpfCnpj
        - ie
        - nome
        - tipoEmitente
        - endereco
      type: object
      properties:
        tipoDocumento:
          description: "Tipo do documento de identificação, se é CPF ou CNPJ"
          $ref: '#/components/schemas/TipoDocumentoDto'
        cpfCnpj:
          description: Documento de Identificação
          type: string
        ie:
          description: "Inscrição estadual, informar quando possuir, ou ISENTO quando\
            \ isento"
          type: string
        nome:
          description: Nome da empresa
          type: string
        nomeFantasia:
          description: Nome fantasia da empresa
          type: string
        email:
          description: E-mail da empresa
          type: string
        telefone:
          description: Telefone da empresa
          type: string
        tipoEmitente:
          description: Tipo Emitente
          $ref: '#/components/schemas/TipoEmitenteDto'
        crt:
          description: Tipo de CRT
          $ref: '#/components/schemas/TipoCrtDto'
        rntrc:
          description: Número do RNTRC
          type: string
        endereco:
          description: Endereço da empresa
          $ref: '#/components/schemas/EnderecoDto'
        cpfCnpjContabilidade:
          description: CPF ou CNPJ da contabilidade responsável pela empresa
          type: string
        emailContabilidade:
          description: E-mail da contabilidade responsável pela empresa
          type: string
        telefoneContabilidade:
          description: Telefone da contabilidade responsável pela empresa
          type: string
        emailsAlternativos:
          description: Lista de e-mails alternativos da empresa
          type: array
          items:
            type: string
        cnae:
          $ref: '#/components/schemas/CnaeDto'
      example:
        tipoDocumento: CNPJ
        cpfCnpj: '01234567890123'
        ie: 12345678901234
        nome: Empresa de Testes
        nomeFantasia: Testinho
        email: empresa@teste.com
        telefone: 81999999999
        tipoEmitente: SERVICO
        crt: SIMPLES_NACIONAL
        rntrc: 12345678
        endereco:
          logradouro: Rua que a empresa Reside
          numero: SN
          codigoMunicipio: 51553
          municipio: Recife
          codigoUf: 51
          uf: PE
          cep: 52000000
        cpfCnpjContabilidade: '012345678970'
        emailContabilidade: contabilidade@teste.com
        telefoneContabilidade: 81999999999
        emailsAlternativos:
          - alt1@teste.com
    CriarOrganizacaoAcessoDto:
      description: "DTO de Organização Acesso, usado para a ação de cadastramento"
      required:
        - perfil
        - login
      type: object
      properties:
        perfil:
          description: Perfil de permissão do Acesso que está sendo criado
          type: string
        login:
          description: Login do usuário para o qual está sendo criado o Acesso
          type: string
      example:
        perfil: ADMIN
        login: usuarioValido@teste.com
    CriarOrganizacaoDto:
      description: "DTO de Organização, usado para a ação de cadastramento"
      required:
        - emailFinanceiro
        - nomeResponsavel
        - loginUsuarioAdministrador
        - empresa
      type: object
      properties:
        emailFinanceiro:
          description: Email do setor financeiro
          type: string
        nomeResponsavel:
          description: Nome do Responsável no setor financeiro
          type: string
        loginUsuarioAdministrador:
          description: Login do usuário administrador do sistema
          type: string
        empresa:
          $ref: '#/components/schemas/CriarEmpresaDto'
      example:
        emailFinanceiro: teste@teste.com
        nomeResponsavel: Responsavel Financeiro
        loginUsuarioAdministrador: usuario@valido.com
        empresa:
          tipoDocumento: CNPJ
          cpfCnpj: '01234567890123'
          ie: 12345678901234
          nome: Empresa de Testes
          nomeFantasia: Testinho
          email: empresa@teste.com
          telefone: 81999999999
          tipoEmitente: SERVICO
          crt: SIMPLES_NACIONAL
          rntrc: 12345678
          endereco:
            logradouro: Rua que a empresa Reside
            numero: SN
            codigoMunicipio: 51553
            municipio: Recife
            codigoUf: 51
            uf: PE
            cep: 52000000
    EmpresaDto:
      description: "DTO de Empresa\r\nRepresenta os dados de uma empresa para transferê\
        ncia entre camadas."
      type: object
      properties:
        id:
          description: Identificador único da empresa
          type: string
        dataUltimaAtualizacao:
          description: Data da última atualização dos dados da empresa
          type: string
          format: date-time
        tipoDocumento:
          description: "Tipo de documento da empresa (CNPJ, CPF, etc)"
          $ref: '#/components/schemas/TipoDocumento'
        cpfCnpj:
          description: CPF ou CNPJ da empresa
          type: string
        ie:
          description: Inscrição estadual
          type: string
        nome:
          description: Nome da empresa
          type: string
        nomeFantasia:
          description: Nome fantasia da empresa
          type: string
        email:
          description: E-mail principal da empresa
          type: string
        telefone:
          description: Telefone principal da empresa
          type: string
        tipoEmitente:
          description: Tipo de emitente
          $ref: '#/components/schemas/TipoEmitenteDto'
        crt:
          description: Código do regime tributário
          $ref: '#/components/schemas/TipoCrtDto'
        rntrc:
          description: Número do RNTRC
          type: string
        situacaoAtivacao:
          description: Situação de ativação da empresa
          $ref: '#/components/schemas/SituacaoAtivacaoDto'
        logomarca:
          description: Logomarca da empresa
          type: string
        empresaCte:
          description: Código da empresa CT-e
          type: string
        empresaCteHom:
          description: Código da empresa CT-e em ambiente de homologação
          type: string
        empresaMdfe:
          description: Código da empresa MDF-e
          type: string
        empresaMdfeHom:
          description: Código da empresa MDF-e em ambiente de homologação
          type: string
        organizacao:
          description: Organização associada à empresa
          $ref: '#/components/schemas/OrganizacaoDtoReduzido'
        certificado:
          description: Certificado digital da empresa
          $ref: '#/components/schemas/CertificadoDto'
        endereco:
          description: Endereço da empresa
          $ref: '#/components/schemas/EnderecoDto'
        matriz:
          description: Indica se a empresa é matriz
          type: boolean
        cpfCnpjContabilidade:
          description: CPF ou CNPJ da contabilidade responsável pela empresa
          type: string
        emailContabilidade:
          description: E-mail da contabilidade responsável pela empresa
          type: string
        telefoneContabilidade:
          description: Telefone da contabilidade responsável pela empresa
          type: string
        emailsAlternativos:
          description: Lista de e-mails alternativos da empresa
          type: array
          items:
            type: string
    EmpresaDtoLista:
      description: "DTO de Empresa, usado nas operações de listagem.\r\nRepresenta\
        \ os dados resumidos de uma empresa para exibição em listas."
      type: object
      properties:
        id:
          description: Identificador único da empresa
          type: string
        dataUltimaAtualizacao:
          description: Data da última atualização dos dados da empresa
          type: string
          format: date-time
        cpfCnpj:
          description: CPF ou CNPJ da empresa
          type: string
        ie:
          description: Inscrição estadual
          type: string
        nome:
          description: Nome da empresa
          type: string
        nomeFantasia:
          description: Nome fantasia da empresa
          type: string
        email:
          description: E-mail principal da empresa
          type: string
        uf:
          description: UF da empresa
          type: string
        municipio:
          description: Município da empresa
          type: string
        tipoEmitente:
          description: Tipo de emitente
          $ref: '#/components/schemas/TipoEmitenteDto'
        crt:
          description: Código do regime tributário
          $ref: '#/components/schemas/TipoCrtDto'
        rntrc:
          description: Número do RNTRC
          type: string
        situacaoAtivacao:
          description: Situação de ativação da empresa
          $ref: '#/components/schemas/SituacaoAtivacaoDto'
        tipoCertificado:
          description: Tipo do certificado digital
          type: string
        matriz:
          description: Indica se a empresa é matriz
          type: boolean
      example:
        id: UUID
        dataUltimaAtualizacao: 2024-12-10 16:12:00
        cpfCnpj: '01234567890123'
        ie: 12345678901234
        nome: Empresa de Teste
        nomeFantasia: Testinho
        email: emailEmpresa@teste.com
        uf: PE
        municipio: Recife
        tipoEmitente: SERVICO
        situacaoAtivacao: ATIVADA
        tipoCertificado: A1
        matriz: true
    EmpresaDtoReduzido:
      description: "DTO de Empresa reduzido.\r\nUsado para retornar dados resumidos\
        \ de uma empresa em outras entidades."
      type: object
      properties:
        id:
          description: Identificador único da empresa
          type: string
        dataUltimaAtualizacao:
          description: Data da última atualização dos dados da empresa
          type: string
          format: date-time
        cpfCnpj:
          description: CPF ou CNPJ da empresa
          type: string
        ie:
          description: Inscrição estadual
          type: string
        nome:
          description: Nome da empresa
          type: string
        nomeFantasia:
          description: Nome fantasia da empresa
          type: string
        uf:
          description: UF da empresa
          type: string
        municipio:
          description: Município da empresa
          type: string
        empresaCte:
          description: Código da empresa CT-e
          type: string
        empresaCteHom:
          description: Código da empresa CT-e em ambiente de homologação
          type: string
        empresaMdfe:
          description: Código da empresa MDF-e
          type: string
        empresaMdfeHom:
          description: Código da empresa MDF-e em ambiente de homologação
          type: string
        matriz:
          description: Indica se a empresa é matriz
          type: boolean
      example:
        id: UUID
        dataUltimaAtualizacao: 2024-12-10 16:12:00
        cpfCnpj: '01234567890123'
        ie: 12345678901234
        nome: Empresa de Teste
        nomeFantasia: Testinho
        uf: PE
        municipio: Recife
        empresaCte: UUID
        empresaCteHom: UUID
        empresaMdfe: UUID
        empresaMdfeHom: UUID
        matriz: true
        cpfCnpjContabilidade: '012345678970'
        emailContabilidade: contabilidade@teste.com
        telefoneContabilidade: 81999999999
        emailsAlternativos:
          - alt1@teste.com
    EmpresaProdutoLogDto:
      description: "DTO de log de operações de produtos da empresa.\r\nUtilizado para\
        \ transferir informações de logs de ações realizadas em produtos vinculados\
        \ à empresa."
      type: object
      properties:
        id:
          description: Identificador do log
          type: string
        dataCriacao:
          description: Data de criação do log
          type: string
          format: date-time
        produto:
          description: Produto relacionado ao log
          type: string
        operacao:
          description: Operação realizada
          type: string
        sucesso:
          description: Indica se a operação foi realizada com sucesso
          type: boolean
        producao:
          description: Indica se a operação foi realizada em produção
          type: boolean
        mensagem:
          description: Mensagem adicional do log
          type: string
      example:
        id: UUID
        dataCriacao: 2024-12-10 16:12:00
        produto: CTE
        operacao: CRIAR
        sucesso: true
    EnderecoDto:
      description: DTO de Endereço
      required:
        - logradouro
        - numero
        - codigoMunicipio
        - municipio
        - codigoUf
        - uf
        - bairro
      type: object
      properties:
        logradouro:
          description: Logradouro
          type: string
        cep:
          description: CEP
          type: string
        numero:
          description: Número
          type: string
        codigoMunicipio:
          description: "Codigo Municipio, IGBE"
          type: string
        municipio:
          description: Nome Municipio
          type: string
        codigoUf:
          description: "Código da UF, IBGE"
          type: string
        uf:
          description: Sigla da UF
          type: string
        bairro:
          description: Bairro
          type: string
        complemento:
          description: Complemento
          type: string
      example:
        logradouro: Rua que a empresa Reside
        numero: SN
        codigoMunicipio: 51553
        municipio: Recife
        codigoUf: 51
        uf: PE
        cep: 52000000
    OrganizacaoAcessoDto:
      description: "DTO de Acesso à Organização.\r\nUsado para representar os dados\
        \ de acesso/permissão de um usuário em uma organização."
      type: object
      properties:
        id:
          description: Identificador do acesso
          type: string
        login:
          description: Login do usuário
          type: string
        perfil:
          description: Perfil de permissão do acesso
          type: string
        usuario:
          description: Usuário associado ao acesso
          $ref: '#/components/schemas/UsuarioDtoReduzido'
      example:
        id: UUID
        login: loginTest@teste.com
        perfil: ADMIN
        usuario:
          id: 17
          login: loginTest@teste.com
          nome: usuarioTesteMock
          email: loginTest@teste.com
    OrganizacaoAcessoDtoReduzido:
      description: "DTO de Organização Acesso, usado principalmente para quando precisar\
        \ trazer os dados de Organização Acesso,\r\nporém como parte da informaçã\
        o de outra entidade, possuir menor quantidade de dados"
      type: object
      properties:
        perfil:
          description: Perfil de permissão do Acesso
          type: string
        usuario:
          description: Dados do usuário vinculado ao Acesso
          $ref: '#/components/schemas/UsuarioDtoReduzido'
      example:
        perfil: ADMIN
        usuario:
          id: 17
          login: loginTest@teste.com
          nome: usuarioTesteMock
          email: loginTest@teste.com
    OrganizacaoDto:
      description: "DTO de Organização.\r\nRepresenta os dados de uma organização\
        \ para transferência entre camadas."
      type: object
      properties:
        id:
          description: Identificador único da organização
          type: string
        cpfCnpj:
          description: CPF ou CNPJ da organização
          type: string
        ie:
          description: Inscrição estadual
          type: string
        nome:
          description: Nome da organização
          type: string
        emailFinanceiro:
          description: E-mail financeiro da organização
          type: string
        nomeResponsavel:
          description: Nome do responsável pela organização
          type: string
        usuarioAdministrador:
          description: Usuário administrador da organização
          $ref: '#/components/schemas/UsuarioDtoReduzido'
        dataBloqueioSistemaPagamento:
          description: Data de bloqueio do sistema de pagamento
          type: string
          format: date-time
        dataDesativacaoSistemaPagamento:
          description: Data de desativação do sistema de pagamento
          type: string
          format: date-time
        situacaoSistemaPagamento:
          description: Situação do sistema de pagamento
          $ref: '#/components/schemas/SituacaoClienteSistemaPagamentoDto'
        idSistemaPagamento:
          description: Identificador do sistema de pagamento
          type: string
        mrr:
          description: Receita recorrente mensal (MRR)
          type: number
          format: double
        perfilConta:
          description: Perfil da conta
          $ref: '#/components/schemas/PerfilContaDto'
        organizacaoAccessos:
          description: Lista de acessos da organização
          type: array
          items:
            $ref: '#/components/schemas/OrganizacaoAcessoDtoReduzido'
        empresas:
          description: Lista de empresas da organização
          type: array
          items:
            $ref: '#/components/schemas/EmpresaDtoReduzido'
        tenantCte:
          description: Tenant CT-e
          $ref: '#/components/schemas/TenantDtoReduzido'
        tenantMdfe:
          description: Tenant MDF-e
          $ref: '#/components/schemas/TenantDtoReduzido'
        tenantEdi:
          description: Tenant EDI
          $ref: '#/components/schemas/TenantDtoReduzido'
      example:
        id: UUID
        cpfCnpj: '01234567890123'
        ie: 12345678901234
        nome: Organizacao XYZ
        emailFinanceiro: financeiro@teste.com
        nomeResponsavel: Responsável Financeiro
        idSistemaPagamento: SL123
        usuarioAdministrador:
          id: 17
          login: loginTest@teste.com
          nome: usuarioTesteMock
          email: loginTest@teste.com
        situacaoSistemaPagamento: ATIVO
        mrr: 0
        organizacaoAccessos:
          - perfil: ADMIN
            usuario:
              id: 17
              login: loginTest@teste.com
              nome: usuarioTesteMock
              email: loginTest@teste.com
        empresas:
          - id: UUID
            dataUltimaAtualizacao: 2024-12-10 16:12:00
            cpfCnpj: '01234567890123'
            ie: 12345678901234
            nome: Empresa de Teste
            nomeFantasia: Testinho
            uf: PE
            municipio: Recife
            empresaCte: UUID
            matriz: true
        tenantCte: UUID
    OrganizacaoDtoLista:
      description: "DTO de lista de Organizações.\r\nUsado para retornar dados resumidos\
        \ de várias organizações."
      type: object
      properties:
        id:
          description: Identificador único da organização
          type: string
        cpfCnpj:
          description: CPF ou CNPJ da organização
          type: string
        ie:
          description: Inscrição estadual
          type: string
        nome:
          description: Nome da organização
          type: string
        usuarioAdministrador:
          description: Usuário administrador da organização
          $ref: '#/components/schemas/UsuarioDtoReduzido'
        dataBloqueioSistemaPagamento:
          description: Data de bloqueio do sistema de pagamento
          type: string
          format: date-time
        dataDesativacaoSistemaPagamento:
          description: Data de desativação do sistema de pagamento
          type: string
          format: date-time
        situacaoSistemaPagamento:
          description: Situação do sistema de pagamento
          $ref: '#/components/schemas/SituacaoClienteSistemaPagamentoDto'
        idSistemaPagamento:
          description: Identificador do sistema de pagamento
          type: string
        mrr:
          description: Receita recorrente mensal (MRR)
          type: number
          format: double
        perfilConta:
          description: Perfil da conta
          $ref: '#/components/schemas/PerfilContaDto'
        tenantCte:
          description: Tenant CT-e
          $ref: '#/components/schemas/TenantDtoReduzido'
        tenantMdfe:
          description: Tenant MDF-e
          $ref: '#/components/schemas/TenantDtoReduzido'
        tenantEdi:
          description: Tenant EDI
          $ref: '#/components/schemas/TenantDtoReduzido'
        tenantTms:
          description: Tenant TMS
          $ref: '#/components/schemas/TenantDtoReduzido'
        tenantRpa:
          description: Tenant RPA
          $ref: '#/components/schemas/TenantDtoReduzido'
      example:
        id: UUID
        cpfCnpj: '01234567890123'
        ie: 12345678901234
        nome: Organizacao XYZ
        idSistemaPagamento: SL123
        usuarioAdministrador:
          id: 17
          login: loginTest@teste.com
          nome: usuarioTesteMock
          email: loginTest@teste.com
        situacaoSistemaPagamento: ATIVO
        mrr: 0
        tenantCte: UUID
    OrganizacaoDtoReduzido:
      description: "DTO reduzido de Organização.\r\nUsado para retornar dados resumidos\
        \ de uma organização."
      type: object
      properties:
        id:
          description: Identificador único da organização
          type: string
        cpfCnpj:
          description: CPF ou CNPJ da organização
          type: string
        ie:
          description: Inscrição estadual
          type: string
        nome:
          description: Nome da organização
          type: string
        idSistemaPagamento:
          description: Identificador do sistema de pagamento
          type: string
      example:
        id: UUID
        cpfCnpj: '01234567890123'
        ie: 12345678901234
        nome: Organizacao XYZ
        idSistemaPagamento: SL123
    PageMetadata:
      type: object
      properties:
        size:
          type: integer
          format: int64
        number:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
    PerfilContaDto:
      type: string
      enum:
        - TRANSPORTADOR
        - CONTADOR
        - PARCEIRO
    PesquisaDadosDto:
      type: object
      properties:
        idPeriodo:
          type: string
        nome:
          type: string
        email:
          type: string
        telefone:
          type: string
        dataHoraContato:
          type: string
          format: date-time
        produto:
          type: string
        tipoEntradaPesquisa:
          $ref: '#/components/schemas/TipoEntradaPesquisaDto'
    PesquisaPeriodoDto:
      type: object
      properties:
        id:
          type: string
        dataInicio:
          type: string
          format: date-time
        dataFinal:
          type: string
          format: date-time
    SituacaoAtivacaoDto:
      type: string
      enum:
        - ATIVADA
        - DESATIVADA
    SituacaoClienteSistemaPagamentoDto:
      type: string
      enum:
        - ATIVO
        - BLOQUEADO
        - INATIVO
    TenantDtoReduzido:
      type: object
      properties:
        id:
          type: string
        nome:
          type: string
        cpfCnpj:
          type: string
        descricao:
          type: string
        tipoAmbiente:
          $ref: '#/components/schemas/TipoAmbienteDto'
        ativo:
          type: boolean
        desbloqueado:
          type: boolean
        nomePlano:
          type: string
      example:
        id: UUID
        nome: Ambiente de testes
        cpfCnpj: '01234567890123'
        descricao: Ambiente de testes
        tipoAmbiente: PRODUCAO
        ativo: true
        desbloqueado: true
        nomePlano: Emissores 30
    TipoAmbienteDto:
      type: string
      enum:
        - HOMOLOGACAO
        - PRODUCAO
    TipoCertificadoDto:
      type: string
      enum:
        - A1
        - A3
    TipoCrtDto:
      type: string
      enum:
        - SIMPLES_NACIONAL
        - SIMPLES_NACIONAL_EXCESSO
        - NORMAL
        - MEI
    TipoDocumento:
      type: string
      enum:
        - CNPJ
        - CPF
    TipoDocumentoDto:
      type: string
      enum:
        - CNPJ
        - CPF
    TipoEmitenteDto:
      type: string
      enum:
        - SERVICO
        - PROPRIO
        - GLOBALIZADO
    TipoEntradaPesquisaDto:
      type: string
      enum:
        - ACEITE
        - CANCELADA
    UsuarioDtoReduzido:
      type: object
      properties:
        id:
          type: string
        login:
          type: string
        nome:
          type: string
        email:
          type: string
      example:
        id: 17
        login: loginTest@teste.com
        nome: usuarioTesteMock
        email: loginTest@teste.com
    Void:
      type: object
    Error:
      description: Um Objeto de erro
      properties:
        mensagem:
          description: Descrição do erro
          type: string
      type: object
  securitySchemes:
    authorization:
      type: http
      scheme: bearer
      description: "Authorization header using the Bearer scheme. Example: \"Authorization:\
        \ Bearer {token}\""
  responses:
    Unauthorized:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Unauthorized
    Forbidden:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Forbidden
security:
  - authorization: []
